### ISSUE TITLE
A question for my usecase.

### ISSUE THREAD

**Issue by Dethkiller15** [jiriteach/nvpn-router#31]
Would I just route traffic by pointing it to the container? I know you said in the docs to use the container as the default gateway but I do not wish to use it on a macvlan with an exposed IP on my router.

In my use case I don't want it exposed outside the device I would use it on.

I just want the setup to be like so 
Internet/Host < Docker Bridge < VPN container < Separate Docker Bridge < Containers attached to VPN docker Bridge.

I am very much out of my depth as I have little knowledge about networking but I think the script below would do it as well but I am also fairly sure I did it wrong.

```
#!/bin/bash

# Define the source IP, the container's target IP, and the subnet
SUBNET="172.16.0.0/16"
TARGET_CONTAINER_NAME="NordVPN"

# Get the IP address of the target container
TARGET_CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$TARGET_CONTAINER_NAME")

if [ -z "$TARGET_CONTAINER_IP" ]; then
  echo "Error: Unable to find IP address for container '$TARGET_CONTAINER_NAME'."
  exit 1
fi

# Add a route to direct traffic from the SUBNET to the target container
ip rule add from "$SUBNET" table 200
ip route add default via "$TARGET_CONTAINER_IP" table 200
iptables -D FORWARD 1
```

**Comment by jiriteach** [comment]
So if I understand correctly - in your use case, you are only wanting other Docker containers to route through the NVPN tunnel? No other LAN devices?

**Comment by Dethkiller15** [comment]
> So if I understand correctly - in your use case, you are only wanting other Docker containers to route through the NVPN tunnel? No other LAN devices?

That is correct. however I dont want to use the docker method of using service:nordvpn or container:nordvpn to attach to the container. I would much rather have the option to take the container off the VPN without having to redeploy.

**Comment by jiriteach** [comment]
Ok - then setting the default route for the container is best and yes that approach you have mentioned above could work where you have a script that set the default route. 

Not sure that example you posted above will work - I would need to setup a test to check. Further - its a little different on the Synology's. If I can get a chance in the next few days - I'll try and replicate.

**Comment by Dethkiller15** [comment]
Thanks for the confirmation I will attempt it ether sometime tonight or tomorrow. And I am fairly sure that I have another set of commands that will work. (Had been trying them with the main branch but couldn’t even ping google when I tried it.) I will post them when I find them.

**Comment by Dethkiller15** [comment]
Well that didn't work. sadly the container I am using somehow does not allow the usage off ping but does curl and gives me a could not resolve error when I do "curl ifconfig.io"

I know there is a way to force allowing packets between both bridges but was really hopping to get it with the script I already have with 0 modification besides the variables. :( oh well I have some more commands that may help facilitate communication between the networks. However it is time for me to go to bed and I already have the tabs open for that on another computer I have at work. Will get them later.

**Comment by Dethkiller15** [comment]
Well I found the commands that should facilitate proper communications between the networks.... but that didn't work ether.

I had to remake the NordVPNBridge docker network in order for the script to work properly without needing to do anything to weird in the script itself.

```
docker network create \
  --driver bridge \
  --subnet 172.16.0.0/16 \
  --gateway 172.16.0.1 \
  --opt com.docker.network.bridge.name=nordvpn-bridge \
  NordVPNBridge

```

here is an updated script with my current IP tables and settings.
```
#!/bin/bash

# Set your gateway container name here.
TARGET_CONTAINER_NAME="NordVPN-Router"

# Set your Docker network names here
NETWORK1="bridge" # Needs to be the same network your gateway container is on
NETWORK2="NordVPNBridge" # traffic from this network will be forwarded to the target container.


# Get the IP address of the target container
TARGET_CONTAINER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$TARGET_CONTAINER_NAME")

if [ -z "$TARGET_CONTAINER_IP" ]; then
  echo "Error: Unable to find IP address for container '$TARGET_CONTAINER_NAME'."
  exit 1
fi

# Function to get the bridge interface name from a Docker network name
get_bridge_interface() {
    docker network inspect "$1" -f '{{index .Options "com.docker.network.bridge.name"}}'

}

# Function to get the subnet CIDR from a Docker network name
get_subnet_cidr() {
    docker network inspect "$1" -f '{{range .IPAM.Config}}{{.Subnet}}{{end}}'
}

# Get bridge interfaces and subnets
BRIDGE1=$(get_bridge_interface "$NETWORK1")
BRIDGE2=$(get_bridge_interface "$NETWORK2")
SUBNET1=$(get_subnet_cidr "$NETWORK1")
SUBNET2=$(get_subnet_cidr "$NETWORK2")

# Check if the bridge interfaces and subnets were retrieved successfully
if [ -z "$BRIDGE1" ] || [ -z "$BRIDGE2" ] || [ -z "$SUBNET1" ] || [ -z "$SUBNET2" ]; then
    echo "Error retrieving network information. Please check the network names."
    exit 1
fi

# Add IP routes between networks
echo "Adding routes between $NETWORK1 ($SUBNET1) and $NETWORK2 ($SUBNET2)..."
ip route add "$SUBNET1" dev "$BRIDGE2"
ip route add "$SUBNET2" dev "$BRIDGE1"

# Set up iptables rules to allow traffic between the networks
echo "Setting up iptables rules..."
iptables -I FORWARD -s "$SUBNET1" -d "$SUBNET2" -j ACCEPT
iptables -I FORWARD -s "$SUBNET2" -d "$SUBNET1" -j ACCEPT



# Add a route to direct traffic from the SUBNET to the target container
ip rule add from "$SUBNET2" table 200
ip route add default via "$TARGET_CONTAINER_IP" table 200
iptables -D FORWARD 1


echo "Routing and iptables rules set up successfully between $NETWORK1 and $NETWORK2."

```

**Comment by Dethkiller15** [comment]
I had been trying for well over 48 hours now :(
I am almost thinking that it would be easier to just have it be a weird double VPN allow the specific ports needed to connect to it on the host and then force a specific docker network to have the tun adapter be the parent.

**Comment by Dethkiller15** [comment]
I have 0 clue as to how I didn't find this earlier

https://github.com/kelvin-id/workaround-for-docker-container-network-gateway-restrictions/tree/main

I will see about making my own implementation of this to use this image and finally comment it here.

**Comment by Dethkiller15** [comment]
I used a modified compose from the github mentioned above and nada.

nordvpn-router is still able to do "curl ifconfig.io" and get the VPN IP but the test container cant get anything.

```
version: "3"
services:
  nordvpn-router:
    image: jiriteach/nvpn-router:latest
    container_name: NordVPN-Router
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=your-user
      - PASS=get-your-own
      - COUNTRY=United States
      - GROUP=P2P
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=5 */3 * * *
      - NETWORK=192.168.1.0/24;192.168.2.0/24;172.16.0.0/16;172.18.0.0/16
      - OPENVPN_OPTS=--mute-replay-warnings
      - TZ=US/Chicogo
    restart: unless-stopped
    hostname: nordvpn-router
    networks:
      nordvpn-exit:
        ipv4_address: 172.18.0.255



  vpn-test-ubuntu:
    container_name: VPN-Test-Ubuntu
    image: ubuntu-with-tools
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    hostname: vpn-test-ubuntu
    networks:
      nordvpn-exit:
    command: >-
      sh -c "ip route del default &&
      ip route add default via 172.18.0.255 &&
      tail -f /dev/null"


networks:
  nordvpn-exit:
    driver: bridge
    name: NordVPN-Exit
    ipam:
      config:
        - subnet: 172.18.0.0/16
```
